name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20-bookworm-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci
          npm cache clean --force

      - name: Type check
        run: npm run type-check

      - name: Build project
        run: npm run build
      
      - name: Verify production build
        run: |
          ls -la dist/
          [ -f dist/index.html ] || exit 1

      # Optional: Add caching for faster builds
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-